[ODOO-6276][UPD][account_analytic_currency] - Update on Stg
calyx-servicios/grupopgk pull request #329
Opened 2023-04-12 15:24 UTC by JaviZamoraDev

2023-04-12 17:33 UTC, paradiso95cristian requested changes

2023-04-12 17:33 UTC, paradiso95cristian commented on account_analytic_currency/wizards/manage_currencies.py
> +    #     }
sacar parte comentada

2023-04-12 17:33 UTC, paradiso95cristian commented on account_analytic_currency/wizards/manage_currencies.py
> +from urllib.parse import urlencode
sacar importacion que no se usa

2023-04-13 14:49 UTC, gabbiiperez commented on account_analytic_currency/i18n/es_ARpo
> +msgid ""
Javi fijate que al archivo le falto el .  en la extencion

2023-04-13 15:02 UTC, merged